plugin:
  name: Pretty Cool Analyzer
  description: Note in the entry, must be the POPO of the class that implements SystemPlugin
  version: 1.0.0
  author: John Doe
  license: MIT
  website: https://example-plugin.com

entry:
  controller: Plugin.php

listen:
  trades: false

